### ISSUE TITLE
The site

### ISSUE THREAD

**Issue by benpete22** [jeffjet24/MackChamberlain.codes#15]
Real dumb. Needs more cats. I really do not see the point of it the way it is now...

**Comment by jeffjet24** [comment]
Go make your own website then!

**Comment by jeffjet24** [comment]
closing issue, because it was a troll

**Comment by benpete22** [comment]
This issue has not been resolved. I do not see any cats on the page.

**Comment by jeffjet24** [comment]
get out of here if you dont have anything useful to contribute. :-1: 
BTW, there is a cat on every page. the Octocat to be exact...
