### ISSUE TITLE
Review/Update Resume

### ISSUE THREAD

**Issue by iamMANN** [jeffjet24/MackChamberlain.codes#19]
I like that it's now available as a PDF, but the "Technical Proficiencies" section is split between the page break. I would say go ahead and expand to the second page. Maybe expand a bit more of work experience? Or condense it to a single page. IDK

**Comment by jeffjet24** [comment]
Thanks for Catching that! I added my website to my resume, and I didn't notice that it split up the technical proficiencies area. :) 
I think I am gonna try to get it to fit it in as much space as possible, while still looking good. 
However, I think I am gonna leave the additional training stuff on the second page. 
Thanks for your input! :+1:

**Comment by jeffjet24** [comment]
I finished updating my resume and getting it ready for the job fairs next week
