### ISSUE TITLE
Background Image Scaling

### ISSUE THREAD

**Issue by iamMANN** [jeffjet24/MackChamberlain.codes#22]
The background image on some pages don't stretch correctly on some browsers. Especially the Education page, for some reason it's different then the other pages on IE 10 and Firefox.

Windows 7 IE 10
![image](https://cloud.githubusercontent.com/assets/1343173/9822031/bdacc7e2-5883-11e5-8904-261dc35f1693.png)

Windows 7 Firefox
![image](https://cloud.githubusercontent.com/assets/1343173/9822304/3c8ec9e2-5885-11e5-95c4-a8a211fdb38e.png)

I don't know if the header needs changing for mobile. All the links at the top for the different pages seem to all bunch together. I don't know anything about optimizing for mobile, but may need more work.

Chrome on Android
![screenshot_2015-09-11-13-03-02](https://cloud.githubusercontent.com/assets/1343173/9822426/fbe9cd28-5885-11e5-8059-16b973e384c8.png)

**Comment by jeffjet24** [comment]
I have pushed an update to now have the background stretch on Firefox on Windows 7. I have to check IE 11 later. But it looks like IE will need the most work.

**Comment by jeffjet24** [comment]
I have verified that the wallpaper stretches properly on IE 11, and it also works on Microsoft Edge as well. 
The stacking of the links on mobile is intended for now. I think it dynamically changes accordingly, and on most devices will end up in a 2 column or 1 column list. 
So I am closing this issue.
